### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by CWWhitney** [EduardoFernandezC/Cover-Decision#6]
The title of the repo is misspelled: 'abaut' should be 'about'

**Comment by CWWhitney** [comment]
@EduardoFernandezC did you seem my comment here?

**Comment by EduardoFernandezC** [comment]
Hi Cory!

Yes, I have seen it. But, I got some troubles in downloading the file
through R. When I use R, the file is “corrupted” but if I use my browser it
is ok.

I don't know why... I need some time to fix it out.

Cheers
Eduardo

**Comment by CWWhitney** [comment]
I will be in soon and we can have a look together.

**Comment by CWWhitney** [comment]
Closed but the title description still says 'Decision analysis project abaut the use of covers in sweet cherries’
‘abaut' should be ‘about’ 
I cannot access this

**Comment by EduardoFernandezC** [comment]
Now it says "about"..
