### ISSUE TITLE
Getting others on board

### ISSUE THREAD

**Issue by CWWhitney** [EduardoFernandezC/Cover-Decision#7]
@EduardoFernandezC shall we get Italo and Gonzalo on board with github? I think this could be very useful for our long distance communication. I just started learning about 'code review' and see why pull requests are revolutionary!!! MUCH MUCH MUCH preferable to direct pushing. More on that soon.

**Comment by EduardoFernandezC** [comment]
@CWWhitney I think that would be useful. But I am not sure if they use GitHub.... I will ask them first!

**Comment by CWWhitney** [comment]
Any word?
